package org.skellig.teststep.processor.web3

import org.web3j.abi.TypeReference
import org.web3j.abi.datatypes.*
import org.web3j.abi.datatypes.Int
import org.web3j.abi.datatypes.generated.*
import org.web3j.abi.datatypes.primitive.Byte

internal class TypeReferencesMap(additionalTypeRefs: Map<String, TypeReference<out Type<out Any>>>) {
    companion object {
        val typeReferences = mutableMapOf(
            Pair("address", object : TypeReference<Address>() {}),
            Pair("web3Byte", object : TypeReference<Byte>() {}),
            Pair("dynamicBytes", object : TypeReference<DynamicBytes>() {}),
            Pair("web3Int", object : TypeReference<Int>() {}),
            Pair("int256", object : TypeReference<Int256>() {}),
            Pair("int112", object : TypeReference<Int112>() {}),
            Pair("int8", object : TypeReference<Int8>() {}),
            Pair("int136", object : TypeReference<Int136>() {}),
            Pair("int152", object : TypeReference<Int152>() {}),
            Pair("int80", object : TypeReference<Int80>() {}),
            Pair("int232", object : TypeReference<Int232>() {}),
            Pair("int176", object : TypeReference<Int176>() {}),
            Pair("int40", object : TypeReference<Int40>() {}),
            Pair("int64", object : TypeReference<Int64>() {}),
            Pair("int216", object : TypeReference<Int216>() {}),
            Pair("int88", object : TypeReference<Int88>() {}),
            Pair("int16", object : TypeReference<Int16>() {}),
            Pair("int192", object : TypeReference<Int192>() {}),
            Pair("int168", object : TypeReference<Int168>() {}),
            Pair("int200", object : TypeReference<Int200>() {}),
            Pair("int104", object : TypeReference<Int104>() {}),
            Pair("int224", object : TypeReference<Int224>() {}),
            Pair("int120", object : TypeReference<Int120>() {}),
            Pair("int240", object : TypeReference<Int240>() {}),
            Pair("int144", object : TypeReference<Int144>() {}),
            Pair("int208", object : TypeReference<Int208>() {}),
            Pair("int72", object : TypeReference<Int72>() {}),
            Pair("int96", object : TypeReference<Int96>() {}),
            Pair("int128", object : TypeReference<Int128>() {}),
            Pair("int248", object : TypeReference<Int248>() {}),
            Pair("int32", object : TypeReference<Int32>() {}),
            Pair("int56", object : TypeReference<Int56>() {}),
            Pair("int24", object : TypeReference<Int24>() {}),
            Pair("int48", object : TypeReference<Int48>() {}),
            Pair("int160", object : TypeReference<Int160>() {}),
            Pair("int184", object : TypeReference<Int184>() {}),
            Pair("uint", object : TypeReference<Uint>() {}),
            Pair("uint72", object : TypeReference<Uint72>() {}),
            Pair("uint56", object : TypeReference<Uint56>() {}),
            Pair("uint32", object : TypeReference<Uint32>() {}),
            Pair("uint96", object : TypeReference<Uint96>() {}),
            Pair("uint136", object : TypeReference<Uint136>() {}),
            Pair("uint256", object : TypeReference<Uint256>() {}),
            Pair("uint216", object : TypeReference<Uint216>() {}),
            Pair("uint16", object : TypeReference<Uint16>() {}),
            Pair("uint152", object : TypeReference<Uint152>() {}),
            Pair("uint112", object : TypeReference<Uint112>() {}),
            Pair("uint232", object : TypeReference<Uint232>() {}),
            Pair("uint176", object : TypeReference<Uint176>() {}),
            Pair("uint40", object : TypeReference<Uint40>() {}),
            Pair("uint192", object : TypeReference<Uint192>() {}),
            Pair("uint80", object : TypeReference<Uint80>() {}),
            Pair("uint48", object : TypeReference<Uint48>() {}),
            Pair("uint24", object : TypeReference<Uint24>() {}),
            Pair("uint88", object : TypeReference<Uint88>() {}),
            Pair("uint64", object : TypeReference<Uint64>() {}),
            Pair("uint248", object : TypeReference<Uint248>() {}),
            Pair("uint104", object : TypeReference<Uint104>() {}),
            Pair("uint224", object : TypeReference<Uint224>() {}),
            Pair("uint168", object : TypeReference<Uint168>() {}),
            Pair("uint208", object : TypeReference<Uint208>() {}),
            Pair("uint128", object : TypeReference<Uint128>() {}),
            Pair("uint240", object : TypeReference<Uint240>() {}),
            Pair("uint184", object : TypeReference<Uint184>() {}),
            Pair("uint8", object : TypeReference<Uint8>() {}),
            Pair("uint160", object : TypeReference<Uint160>() {}),
            Pair("uint200", object : TypeReference<Uint200>() {}),
            Pair("uint144", object : TypeReference<Uint144>() {}),
            Pair("uint120", object : TypeReference<Uint120>() {}),
            Pair("fixed", object : TypeReference<Fixed>() {}),
            Pair("ufixed", object : TypeReference<Ufixed>() {}),
            Pair("web3Bool", object : TypeReference<Bool>() {}),
            Pair("web3String", object : TypeReference<Utf8String>() {}),
            Pair("web3Array", object : TypeReference<DynamicStruct>() {}),

            Pair("address indexed", object : TypeReference<Address>(true) {}),
            Pair("web3Byte indexed", object : TypeReference<Byte>(true) {}),
            Pair("dynamicBytes indexed", object : TypeReference<DynamicBytes>(true) {}),
            Pair("web3Int indexed", object : TypeReference<Int>(true) {}),
            Pair("int256 indexed", object : TypeReference<Int256>(true) {}),
            Pair("int112 indexed", object : TypeReference<Int112>(true) {}),
            Pair("int8 indexed", object : TypeReference<Int8>(true) {}),
            Pair("int136 indexed", object : TypeReference<Int136>(true) {}),
            Pair("int152 indexed", object : TypeReference<Int152>(true) {}),
            Pair("int80 indexed", object : TypeReference<Int80>(true) {}),
            Pair("int232 indexed", object : TypeReference<Int232>(true) {}),
            Pair("int176 indexed", object : TypeReference<Int176>(true) {}),
            Pair("int40 indexed", object : TypeReference<Int40>(true) {}),
            Pair("int64 indexed", object : TypeReference<Int64>(true) {}),
            Pair("int216 indexed", object : TypeReference<Int216>(true) {}),
            Pair("int88 indexed", object : TypeReference<Int88>(true) {}),
            Pair("int16 indexed", object : TypeReference<Int16>(true) {}),
            Pair("int192 indexed", object : TypeReference<Int192>(true) {}),
            Pair("int168 indexed", object : TypeReference<Int168>(true) {}),
            Pair("int200 indexed", object : TypeReference<Int200>(true) {}),
            Pair("int104 indexed", object : TypeReference<Int104>(true) {}),
            Pair("int224 indexed", object : TypeReference<Int224>(true) {}),
            Pair("int120 indexed", object : TypeReference<Int120>(true) {}),
            Pair("int240 indexed", object : TypeReference<Int240>(true) {}),
            Pair("int144 indexed", object : TypeReference<Int144>(true) {}),
            Pair("int208 indexed", object : TypeReference<Int208>(true) {}),
            Pair("int72 indexed", object : TypeReference<Int72>(true) {}),
            Pair("int96 indexed", object : TypeReference<Int96>(true) {}),
            Pair("int128 indexed", object : TypeReference<Int128>(true) {}),
            Pair("int248 indexed", object : TypeReference<Int248>(true) {}),
            Pair("int32 indexed", object : TypeReference<Int32>(true) {}),
            Pair("int56 indexed", object : TypeReference<Int56>(true) {}),
            Pair("int24 indexed", object : TypeReference<Int24>(true) {}),
            Pair("int48 indexed", object : TypeReference<Int48>(true) {}),
            Pair("int160 indexed", object : TypeReference<Int160>(true) {}),
            Pair("int184 indexed", object : TypeReference<Int184>(true) {}),
            Pair("uint indexed", object : TypeReference<Uint>(true) {}),
            Pair("uint72 indexed", object : TypeReference<Uint72>(true) {}),
            Pair("uint56 indexed", object : TypeReference<Uint56>(true) {}),
            Pair("uint32 indexed", object : TypeReference<Uint32>(true) {}),
            Pair("uint96 indexed", object : TypeReference<Uint96>(true) {}),
            Pair("uint136 indexed", object : TypeReference<Uint136>(true) {}),
            Pair("uint256 indexed", object : TypeReference<Uint256>(true) {}),
            Pair("uint216 indexed", object : TypeReference<Uint216>(true) {}),
            Pair("uint16 indexed", object : TypeReference<Uint16>(true) {}),
            Pair("uint152 indexed", object : TypeReference<Uint152>(true) {}),
            Pair("uint112 indexed", object : TypeReference<Uint112>(true) {}),
            Pair("uint232 indexed", object : TypeReference<Uint232>(true) {}),
            Pair("uint176 indexed", object : TypeReference<Uint176>(true) {}),
            Pair("uint40 indexed", object : TypeReference<Uint40>(true) {}),
            Pair("uint192 indexed", object : TypeReference<Uint192>(true) {}),
            Pair("uint80 indexed", object : TypeReference<Uint80>(true) {}),
            Pair("uint48 indexed", object : TypeReference<Uint48>(true) {}),
            Pair("uint24 indexed", object : TypeReference<Uint24>(true) {}),
            Pair("uint88 indexed", object : TypeReference<Uint88>(true) {}),
            Pair("uint64 indexed", object : TypeReference<Uint64>(true) {}),
            Pair("uint248 indexed", object : TypeReference<Uint248>(true) {}),
            Pair("uint104 indexed", object : TypeReference<Uint104>(true) {}),
            Pair("uint224 indexed", object : TypeReference<Uint224>(true) {}),
            Pair("uint168 indexed", object : TypeReference<Uint168>(true) {}),
            Pair("uint208 indexed", object : TypeReference<Uint208>(true) {}),
            Pair("uint128 indexed", object : TypeReference<Uint128>(true) {}),
            Pair("uint240 indexed", object : TypeReference<Uint240>(true) {}),
            Pair("uint184 indexed", object : TypeReference<Uint184>(true) {}),
            Pair("uint8 indexed", object : TypeReference<Uint8>(true) {}),
            Pair("uint160 indexed", object : TypeReference<Uint160>(true) {}),
            Pair("uint200 indexed", object : TypeReference<Uint200>(true) {}),
            Pair("uint144 indexed", object : TypeReference<Uint144>(true) {}),
            Pair("uint120 indexed", object : TypeReference<Uint120>(true) {}),
            Pair("fixed indexed", object : TypeReference<Fixed>(true) {}),
            Pair("ufixed indexed", object : TypeReference<Ufixed>(true) {}),
            Pair("web3Bool indexed", object : TypeReference<Bool>(true) {}),
            Pair("web3String indexed", object : TypeReference<Utf8String>(true) {}),
            Pair("web3Array indexed", object : TypeReference<DynamicStruct>(true) {})
        )
    }

    init {
        additionalTypeRefs.forEach {
            typeReferences[it.key] = it.value
        }
    }

    fun get(typeName: String): TypeReference<out Type<out Any>>? = typeReferences[typeName]

    override fun toString(): String {
        return typeReferences.keys.toString()
    }
}