name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    env:
      MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
    strategy:
      matrix:
#        os: [ ubuntu-latest, windows-latest ]
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.15.0
        with:
          java-version: 17
          maven-version: 3.9.6
          java-distribution: 'oracle'

#      - name: Build and package components
#        run: mvn package -DskipITs=true -DskipTests

      - name: Run unit tests
        run: mvn install -DskipITs=true

      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/site/jacoco/jacoco.xml