name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
#    env:
#      MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
#      MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
    strategy:
      matrix:
        os: [ windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.15.0
        with:
          java-version: 17
          maven-version: 3.9.6
          java-distribution: 'oracle'

#      - name: Build and package components
#        run: mvn package -DskipITs=true -DskipTests

      - name: Run unit tests
        run: mvn install -DskipITs=true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}